### ISSUE TITLE
Convert PDFs to Markdown or Similar

### ISSUE THREAD

**Issue by mollstam** [OpenAgInitiative/gro-hardware#1]
Hello!

This is a great initiative, but I was thinking: it's hard in the spirit of open source to contribute to documentation that is uploaded as PDF, since we don't have access to the source files. Maybe updating it into something like Markdown would be a nice move?

Now, I don't actually have any edits in mind, I haven't even read the whole thing. Just a thought, feel free to ignore it. :grimacing: 

:tada:

**Comment by activescott** [comment]
:+1:

**Comment by tobymurray** [comment]
This seems like a no-brainer. Lowering the barrier of entry for keeping the documentation up to date would go a ways towards keeping it useful. I'd be willing to help if there's some interest in [the existing PR](https://github.com/OpenAgInitiative/gro-hardware/pull/2)

**Comment by activescott** [comment]
Would love to see it on the GitHub ~~wiki~~ as markdown files in the repository itself. Also more than happy to contribute to that. I have a series of pictures and notes on modifications I've made to the enclosure to make it easier too. So it would be cool to be able to allow others to link in such proposed alternatives for others to see too which could be done in github with PRs to the md files in the repository.

**Comment by tobymurray** [comment]
@rcamille5 @dhgood2 - is anybody still watching this repo, or is it obsolete? The documentation seems like an ideal place for the community to contribute in a fashion that doesn't incur too much extra work for you guys but has a ton of gain for us, I'd love to see this addressed (whether it's a "this is dead, move along" or not).

**Comment by sp4ghet** [comment]
I've merged these changes in as part of a big reorganization of the repo, thank you @seanslerner.
