### ISSUE TITLE
No schematics for proto / shield

### ISSUE THREAD

**Issue by barwis** [OpenAgInitiative/gro-hardware#15]
Where can I find those?

**Comment by AdrianLLu** [comment]
Hey barwis, I made a schematic for it here: http://adrianllu.com/2016/04/17/motherboard-build-notes-part-1-micro-controller-protoshield/

**Comment by sp4ghet** [comment]
In the latest commit, I added a link to @AdrianLLu 's wiring as well as JoshSinykin's diagram.
Is it ok to close this issue? 

I'm actually going to close this issue as a duplicate to #8
