### ISSUE TITLE
Bill of Materials does not include mainframe components

### ISSUE THREAD

**Issue by rrfavreau** [OpenAgInitiative/gro-hardware#4]
Is there some reason the PVC boards and other hardware for the frame is not included in the Excel BOM?

**Comment by ferguman** [comment]
There is an item on the Excel BOM named PVC sheet, white, 1/2" thick, 24" x 96".  The link provided for this item  is: http://www.homedepot.com/p/Veranda-HP-1-2-in-x-48-in-x-8-ft-White-PVC-Trim-H120AWS6/205309788.  The PVC parts are to be cut from this sheet of PVC.

**Comment by JeremyThiesen** [comment]
Downloaded most recent BOM and it does not include the PVC sheet item.

**Comment by barwis** [comment]
@JeremyThiesen check the second page in xls sheet, called "Hardware".
