### ISSUE TITLE
PVC equivalent?

### ISSUE THREAD

**Issue by barwis** [OpenAgInitiative/gro-hardware#9]
In the UK, it's either really difficult to get rigid PVC boards this size, or it's extremely expensive.
Can any other materials be used to create motherboard/base board?

**Comment by tobymurray** [comment]
I haven't tried it, but what about marine plywood or similar products? Maybe some vapor barrier over it for good measure?

_EDIT_ I'm in the same situation now, and I'm thinking I'll try vinyl flooring over-top plywood. Looking at the local shop, it's ~0.89$/square foot, so extremely reasonable. The price for PVC sheets was outlandish, and I think vinyl flooring is largely the same material but much thinner. In other projects I've protected wood with vapor barrier, and it has stood up to constant exposure to moisture for over a year without any issues at all.

**Comment by barwis** [comment]
I ended up using stripwood boards (from Homebase). It's more moisture-resistant than mdf, or chipboard, and reasonably cheaper. Better alternative would be marine plywood ( from Wickes ), but I didn't want to spend too much time on it, esiecially since I saw that the food computer V2 will be built with plywood boards, so moisture/water resistancy is not that big deal.
